### ISSUE TITLE
STEP or other CAD files

### ISSUE THREAD

**Issue by IamPete1** [spiderixax/Monocopter#3]
Great Project! Any chance you could share `step` or other CAD files so we can edit. I would like to modify to fit a ArduPilot compatible flight controller.

**Comment by spiderixax** [comment]
I am glad you find it interesting. I have added a STEP file and an f3d file. The f3d file is very messy, but you can see the all the changes.

**Comment by IamPete1** [comment]
Great, Thanks, I will keep you posted.

**Comment by IamPete1** [comment]
![20230205_165644](https://user-images.githubusercontent.com/33176108/216833171-dada29cb-bd24-4458-9671-6dc6621bd99c.jpg)

First prototype of the electronics. Flight controller, BEC, current sensor, ESC, servo, receiver and wifi telemetry module. Its all a bit tight and going to be a PITA to solder, but it all fits. I want to add GPS eventually, I'm not sure where that will go, but can worry about that once its flying. 

What weight did you end up at? I suspect this is going to turn out heavy, I will probably also need to go to a 3s battery to keep the BEC happy. 

What about CG? Is there a ideal place?

Have you ever tried hanging it on a string or having a guide rod of some sort? ArduPilot code development is going to take a fair bit of testing would be nice not to have to rebuild constantly.

Turns out my printer is too small to print the wing in one part. I might move the split line along a bit so the wing root would be on the "fuselage" part. Or maybe it would be easier to just split the wing into two. Not sure yet.

**Comment by spiderixax** [comment]
It's good to see you are making progress!

The weight for me was about 243 grams, and if yours will be any heavier than that, I recommend making the wing bigger. Mine was spinning very fast, a bit too fast in fact, and with a bigger wing it will generate more lift at a certain rotational speed. This brings me to the point of CG - you want it to be as far towards the battery-end as possible to maximise the effective size of the wing (as the monocopter spins around its CG). The precise location is not especially important, but if you place the monocopter with its propeller facing you, the CG should be closer to you than the centre of lift for the monocopter to be stable.

I don't know if you saw [(the video)](https://youtu.be/n9AnnggmyP0), but the 3D printed monocopter can disintegrate at high rotational speeds. Please be careful, this design is still a work-in-progress. You could add some reinforcement rods, or use a higher infill. But then, it would be heavier... So my recommendation is to have a bigger wing (or longer fuselage section, to have a longer effective wing), so that the monocopter spins slower.

Make sure to use a propeller with at least 3 blades. 2-bladed ones randomly break apart in flight (I read in some paper on monocopters that this is due to varying inertia of the blades as the angular momentum vector constantly changes due to the rotation of the entire aircraft...). And 5-inch props work better than 6-inch ones, although if you end up with a monocopter heavier than mine, having a 6-inch prop could actually help, but you would need a CCW-spinning motor for the gyroscopic effect of the large prop to increase the monocopter's angle of attack.

I have fitted my previous monocopter designs with landing gear, you can see some videos of them on my YouTube channel. I stopped using landing gear to save weight when I found out how well hand-launch works. Also, I mostly fly over grass, which is safe to land on (even without motor power in fully drag-powered autorotation).

Out of interest, what filament and printer are you using?

**Comment by IamPete1** [comment]
Thanks! The bit in the picture is 150g already.... although I did just print with stock settings for a trial fit. Got rev 2 on the printer now, with a bit more room for the ESC and BEC. Printer is a Prusa MK3 and there galaxy black PLA, its excellent at hiding print lines.

**Comment by spiderixax** [comment]
That's a lot of mass... Keep in mind that I printed the parts with single walls and 0.8% (gyroid) infill.
